### ISSUE TITLE
date alignments are off

### ISSUE THREAD

**Issue by polygraph-umg** [the-pudding/country-radio-viz#33]
<img width="1277" alt="Screenshot 2023-05-09 at 6 08 53 AM" src="https://github.com/the-pudding/country-radio-viz/assets/67330482/c419bc21-6c98-4f79-ba3a-0efe95183c9b">

**Comment by polygraph-umg** [comment]
same with the next scroll when it highlights

**Comment by jadiehm** [comment]
believe this is on resize when the canvas doesn't get a new width
